# Computational example of detection of serial correlation
library(readxl)
setwd("/Users/pankaj/Downloads")
INRUSD <- read_excel("Xrate.xlsx", sheet = "Data")
head(INRUSD)
n <- length(INRUSD$Xrate)
logxr <- log(INRUSD$Xrate)
logi <- log(INRUSD$IndiaCPI)
logu <- log(INRUSD$USCPI)
lmlogxr <- lm(logxr~logi+logu)
par(mfrow=c(1,2))
library(MASS)
sres <- stdres(lmlogxr)
plot(sres,type="b", ylab = "Standardized residual")
abline(h=0, lty=2)
title("Index plot")
plot(sres[1:(n-1)], sres[2:n], xlab = "Lagged standardized residual",
     ylab = "Standardized residual", type="l")
abline(a=0, b=1, lty=2)
title("Lag plot")
library(lmtest)
dwtest(lmlogxr)
